version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.12.2

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          context: ENV_REACT_BASE_TEMPLATE
          dockerfile: Dockerfile
          path: .
          region: AWS_REGION
          repo: circleci-ecr-orb-demo
          tag: "$CIRCLE_SHA1"
          # profile-name: <my-profile-name>
